version: '3.6'
services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8201'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"1", "tls_cert_file":"/data/vault-volume/certificate.pem", "tls_key_file":"/data/vault-volume/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_TOKEN: 'root'
    volumes:
      - ./scripts:/data/vault-volume/scripts
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id="root"